#!/usr/bin/env python3
"""Generates levels/level1.txt, the Duke Nukem II style sample level.

The level is built from a few helpers instead of being typed by hand, so the
layout can be tweaked by moving numbers around. Coordinates are in 16 px
blocks (2x2 cells); row 0 is the top.

Route: start -> steps -> spike pit -> ladder up a tall wall -> hang bar over
a second spike pit -> access card and checkpoint -> force field door ->
rockets and turrets -> flamethrower jetpack up a shaft -> exit.
"""

import sys

W, H = 140, 26
grid = [["." for _ in range(W)] for _ in range(H)]


def put(x, y, c):
    if 0 <= x < W and 0 <= y < H:
        grid[y][x] = c


def fill(x0, x1, y0, y1, c):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            put(x, y, c)


def ground(x0, x1, top):
    """Solid ground from row `top` down to the bottom of the map."""
    fill(x0, x1, top, H - 1, "#")


def on(x, g, c):
    """Places an object standing on ground whose surface row is g."""
    put(x, g - 1, c)


# 1. Start: flat ground, a merch box to crouch-shoot, gems, a walker.
ground(0, 18, 21)
put(1, 20, "*")
on(3, 21, "P")
for x in (6, 7, 8):
    put(x, 18, "g")
on(11, 21, "m")
on(16, 21, "w")

# 2. Steps: a 2 block ledge, then a 3 block one (needs a full jump).
ground(19, 23, 19)
ground(24, 30, 16)
on(27, 16, "r")
put(25, 13, "g")
put(26, 13, "g")

# 3. Spike pit, jumped over.
ground(31, 34, 22)
fill(31, 33, 21, 21, "^")
fill(34, 34, 16, 21, "H")

# 4. Laser box and a turret, then a tall wall with a ladder.
ground(35, 44, 16)
on(37, 16, "L")
on(42, 16, "t")
put(36, 15, "*")
fill(44, 44, 8, 15, "H")
ground(45, 60, 9)

# 5. Upper deck: a flyer and the first letter.
put(48, 9 - 1, "*")
put(51, 7, "1")
put(55, 4, "f")
on(57, 9, "h")

# 6. Hang bar over a long spike pit (there is a ladder out of the pit).
ground(61, 74, 21)
fill(61, 73, 20, 20, "^")
fill(59, 75, 5, 5, "-")
fill(74, 74, 12, 19, "H")
put(64, 16, "g")
put(68, 16, "g")
put(70, 2, "f")

# 7. Access card and checkpoint, then the force field door.
ground(75, 100, 12)
on(77, 12, "c")
on(81, 12, "k")
on(83, 12, "m")
fill(79, 92, 0, 6, "#")
fill(87, 87, 7, 11, "D")
on(85, 12, "w")

# 8. Behind the door: the second letter, rockets, health, a turret.
put(90, 10, "2")
on(93, 12, "R")
on(99, 12, "t")
for x in (95, 96):
    put(x, 9, "g")

# 9. One-way platforms over a gap, with gems on top.
fill(101, 105, 12, H - 1, ".")
ground(101, 105, 23)
fill(101, 105, 22, 22, "^")
fill(101, 102, 10, 10, "=")
fill(104, 105, 10, 10, "=")
put(101, 8, "g")
put(105, 8, "g")

# 10. Flamethrower, a flyer and walkers, then a shaft only the jetpack climbs.
ground(106, 120, 12)
on(108, 12, "m")
on(111, 12, "w")
on(116, 12, "F")
put(112, 4, "f")
ground(121, 123, 4)
put(119, 7, "3")
put(119, 4, "g")

# 11. Top of the shaft and down to the exit.
ground(124, 139, 8)
put(126, 8 - 1, "*")
on(129, 8, "h")
on(131, 8, "w")
put(134, 5, "g")
on(136, 8, "X")
put(138, 7, "*")

out = ["name=STAGE 1 - ROOFTOP RUN",
       "; generated by tools/mklevel.py - see levels/README.md for the legend"]
out += ["".join(r) for r in grid]
path = sys.argv[1] if len(sys.argv) > 1 else "levels/level1.txt"
with open(path, "w") as f:
    f.write("\n".join(out) + "\n")
print("wrote", path)
