"""Shared helpers for the level scripts in tools/levels/.

Every campaign level is generated by its own script (NN_slug.py) so the
layout can be tweaked by moving numbers around instead of editing a wall of
characters. Coordinates are in 16 px blocks (2 x 2 cells); row 0 is the top.
See levels/README.md for the map characters and the [entities] syntax.
"""

import os
import sys

HEADER_ORDER = ("name", "episode", "theme", "music", "weapon", "par", "flags",
                "respawn_ammo", "rules", "timer", "goal")


def _fmt(v):
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (list, tuple)):
        if v and isinstance(v[0], (list, tuple)):
            return ";".join(",".join(str(c) for c in p) for p in v)
        return ",".join(str(c) for c in v)
    s = str(v)
    if " " in s:
        return '"' + s + '"'
    return s


class Level:
    def __init__(self, w, h, **header):
        self.W, self.H = w, h
        self.grid = [["." for _ in range(w)] for _ in range(h)]
        self.header = header
        self.entities = []

    # --- map ---------------------------------------------------------------
    def put(self, x, y, c):
        if 0 <= x < self.W and 0 <= y < self.H:
            self.grid[y][x] = c

    def get(self, x, y):
        if 0 <= x < self.W and 0 <= y < self.H:
            return self.grid[y][x]
        return "#"

    def fill(self, x0, x1, y0, y1, c):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                self.put(x, y, c)

    def clear(self, x0, x1, y0, y1):
        self.fill(x0, x1, y0, y1, ".")

    def ground(self, x0, x1, top, bottom=None):
        """Solid ground from row `top` down to `bottom` (default: the map's bottom)."""
        self.fill(x0, x1, top, self.H - 1 if bottom is None else bottom, "#")

    def on(self, x, g, c):
        """Places an object standing on ground whose surface row is g."""
        self.put(x, g - 1, c)

    def row(self, x0, x1, y, c):
        self.fill(x0, x1, y, y, c)

    def col(self, x, y0, y1, c):
        self.fill(x, x, y0, y1, c)

    # --- entities ----------------------------------------------------------
    def at(self, kind, x=None, y=None, /, *ids, **keys):
        """Adds an `@ kind [id...] [x y] key=value` line."""
        parts = ["@", kind]
        parts += [str(i) for i in ids]
        if x is not None:
            parts += [str(x), str(y)]
        for k, v in keys.items():
            if v is None:
                continue
            parts.append("%s=%s" % (k.rstrip("_"), _fmt(v)))
        self.entities.append(" ".join(parts))
        return self

    # --- output ------------------------------------------------------------
    def text(self, source):
        out = []
        for k in HEADER_ORDER:
            if k in self.header:
                out.append("%s=%s" % (k, self.header[k]))
        for k, v in self.header.items():
            if k not in HEADER_ORDER:
                out.append("%s=%s" % (k, v))
        out.append("; generated by %s - see levels/README.md for the legend" % source)
        out.append("[map]")
        out += ["".join(r) for r in self.grid]
        if self.entities:
            out.append("[entities]")
            out += self.entities
        return "\n".join(out) + "\n"

    def write(self, script_file, out_name):
        root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(script_file))))
        path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, "levels", out_name)
        src = "tools/levels/" + os.path.basename(script_file)
        with open(path, "w") as f:
            f.write(self.text(src))
        print("wrote", path)
